### PR TITLE
Initial translation to braziliam portuguese

### PR DESCRIPTION
**Pull request by liquuid**

### CODE REVIEW

**Comment by efeefe** [comment]
For after the PT-BR PR: we should standardize in regard to capital letters or not terms like SSH, SSL, P2P and Subutai.

**Comment by liquuid** [comment]
@efeefe I don't like "bandeja". On windows world this kind of "tray app" are called "Notification App". The "sys tray" area are called "Notification Area". [1] 

I made some research and on modern Linux Desktop Enviroments, the systray is dead on Gnome 3.26, by default.  The new name is Indicator Applets, but need a extension for that [2]. On KDE ( Plasma  ) and OSX the name systray don't changed.

About Idioma, agreed
Yes, we need discuss Anfitrião, definitely

I need integrate a spell checker on my Atom editor :-D

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/ee330740(v=vs.85).aspx
[2] http://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray

**Comment by crioto** [comment]
@efeefe Waiting for you to complete review procedure. Tag me or @Lezh1k when you approve please. Thanks.

**Comment by efeefe** [comment]
@crioto done.

**Pull request merged**
